import { spawn } from "node:child_process";
import { randomUUID } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadPrimeArtifactLock, verifyPrimeArtifact } from "./artifact-lock.js";
export class PrimeP4DevelopmentError extends Error { readonly stage: string | undefined; constructor(stage?: string) { super("Prime P4 development daemon is unavailable"); this.stage = stage; } }
export async function runPrimeP4DevelopmentSmoke(primeSourceRoot: string): Promise<Readonly<{ activeSessionId: string; cursor: Readonly<{ generation: string; sequence: number }> }>> {
  const workspace = await mkdtemp(join(tmpdir(), "asterion-p4-"));
  let stage: string | undefined;
  try { const lock = await loadPrimeArtifactLock(new URL("../../resources/prime-artifact-lock.json", import.meta.url)); if (lock.package_name !== "@earendil-works/pi-coding-agent" || lock.package_version !== "0.7.1") throw new Error(); await verifyPrimeArtifact(primeSourceRoot, lock); const socket = join(workspace, "d.sock"); if (process.platform !== "win32" && Buffer.byteLength(socket) >= 104) throw new Error(); const main = fileURLToPath(new URL("./p4-development-main.js", import.meta.url)); const env = Object.fromEntries(["PATH", "HOME", "TMPDIR", "LANG"].flatMap((key) => typeof process.env[key] === "string" ? [[key, process.env[key]]] : [])); const child = spawn(process.execPath, [main, primeSourceRoot, workspace, socket], { stdio: ["ignore", "pipe", "ignore", "pipe"], env }); const output = await new Promise<string>((resolve, reject) => { let body = "", stages = ""; const timer = setTimeout(() => { child.kill("SIGTERM"); setTimeout(() => child.kill("SIGKILL"), 500); reject(new Error()); }, 15_000); child.stdout?.on("data", (v: Buffer) => body += v.toString("utf8")); child.stdio[3]?.on("data", (v: Buffer) => stages += v.toString("utf8")); child.once("close", (code) => { clearTimeout(timer); for (const candidate of stages.split("\n")) if (/^[a-z-]+(?::error)?$/.test(candidate)) stage = candidate; code === 143 ? resolve(body) : reject(new Error()); }); child.once("error", reject); }); const value = JSON.parse(output) as { activeSessionId?: unknown; cursor?: { generation?: unknown; sequence?: unknown } }; if (typeof value.activeSessionId !== "string" || typeof value.cursor?.generation !== "string" || !Number.isSafeInteger(value.cursor.sequence)) throw new Error(); const sequence = value.cursor.sequence as number; return Object.freeze({ activeSessionId: value.activeSessionId, cursor: Object.freeze({ generation: value.cursor.generation, sequence }) }); } catch { throw new PrimeP4DevelopmentError(stage); } finally { await rm(workspace, { recursive: true, force: true }); }
}
