"""Closed, body-free operation protocol contracts."""

from asterion.operation.protocol import (
    EFFECT_COUNTERS,
    OPERATION_FEATURE_IDS,
    OPERATION_PROTOCOL,
    OperationProtocolError,
    OperationReceipt,
    OperationRequestDescriptor,
    OperationTransaction,
    validate_operation_receipt,
    validate_operation_request_descriptor,
    validate_operation_transaction,
)
from asterion.operation.auth import (
    AuthOperationError,
    AuthOperationService,
    AuthStatus,
    AuthStorageBackend,
    OAuthRefresher,
    validate_auth_request,
)
from asterion.operation.model_selection import (
    ModelCatalog,
    ModelSelection,
    ModelSelectionOperationError,
    ModelSelectionOperationService,
    ModelSelectionStore,
    ModelSelectionStoreReceipt,
    validate_model_selection_request,
)
from asterion.operation.settings import (
    KeybindingRecord,
    OperationServiceError,
    PreferenceRecord,
    PreferenceReceipt,
    PreferenceStore,
    PreferenceStoreSnapshot,
    SettingsAllowlist,
    SettingsOperationService,
    validate_settings_keybindings_request,
)

__all__ = [
    "EFFECT_COUNTERS",
    "OPERATION_FEATURE_IDS",
    "OPERATION_PROTOCOL",
    "OperationProtocolError",
    "OperationReceipt",
    "OperationRequestDescriptor",
    "OperationTransaction",
    "validate_operation_receipt",
    "validate_operation_request_descriptor",
    "validate_operation_transaction",
    "AuthOperationError",
    "AuthOperationService",
    "AuthStatus",
    "AuthStorageBackend",
    "OAuthRefresher",
    "validate_auth_request",
    "ModelCatalog",
    "ModelSelection",
    "ModelSelectionOperationError",
    "ModelSelectionOperationService",
    "ModelSelectionStore",
    "ModelSelectionStoreReceipt",
    "validate_model_selection_request",
    "KeybindingRecord",
    "OperationServiceError",
    "PreferenceRecord",
    "PreferenceReceipt",
    "PreferenceStore",
    "PreferenceStoreSnapshot",
    "SettingsAllowlist",
    "SettingsOperationService",
    "validate_settings_keybindings_request",
]
